### PR TITLE
Update functions.php

### PR DESCRIPTION
**Pull request by fardina**
Warning: array_column() expects parameter 1 to be array, null given in .../functions.php line 13

### CODE REVIEW

**Comment by pupi1985** [comment]
Hey! Thanks for this. I've fixed the issue initializing the option... for some reason there was no initialization :shrug:

**Comment by fardina** [comment]
Hi @pupi1985, Thank you for the plugin. There is another issue for me after using the plugin. After fresh installation and enabling the plugin, I found out that moderators and editors(who could confirm questions, answers ,... ) don't have access to the moderate page. It shows the error: only admins have permissions to access this page. By disabling the plugin the error disappears.

**Comment by pupi1985** [comment]
This should have been fixed in v1.5.2

**Comment by pupi1985** [comment]
No, just use v1.5.2, as I stated in my previous comment

**Pull request closed without merging**
